[package]
name = "caesar_rust"
version = "0.1.0"
authors = ["Bookieman <altashana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"